version: "3.8"
services:
  mongo:
    container_name: mongo
    image: 'mongo'
  server:
    container_name: server
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
